/* tslint:disable */
/* eslint-disable */
/**
 * ES 物件API
 * （株）いい生活 が提供予定の 物件情報API のインターフェイス仕様書  いい物件Oneに登録した賃貸物件情報を参照する物件参照API仕様について定める。  ※1: 開発中のため、実際のリリース時の仕様は異なる場合がございます。  ※2: 売買物件に関する仕様に関してはα版であり、今後大きな仕様の見直しを行う可能性がございます。  ## リソース仕様  ### 通信仕様  HTTP/2 および HTTP/1.1 をサポートする。通信はTLSで暗号化されたHTTPSのみを許可する。  ### リクエストヘッダ  リクエストヘッダには以下の指定を必須とする。  | No. | リクエストヘッダのフィールド名 | 指定値 | |:---:|:-------------------------------|:-------| | 1 | Accept | application/json | | 2 | X-Api-Key | 弊社が指定するキー。ご利用のお客様を特定するためのもの。 |  Acceptヘッダには、常にapplication/json を指定する。 これにより、レスポンスがJSONであることを指示する。  ### データフォーマットと文字コード  データフォーマットはJSON、文字コードはUTF-8とする。  ### データ型  通常のJSONの型以外に擬似型としていくつかのデータ型を用意している。 これは、JSON標準では表現しきれないデータや、不動産特有のデータを扱うために定義したもので使用する。 また、ここに記載の無いデータ型については、 OpenAPI Specification (Version 3.0.2) の DataTypes に準拠する。  * [DataTypes](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types)   | No. | 型 | 説明 | |:---:|:---|:-----| | 1 | string | JSON標準の文字列 | | 2 | int | JSON標準の整数 | | 3 | float | JSON標準の浮動小数点数 | | 4 | bool | JSON標準の真偽値 | | 5 | datetime | ISO8611フォーマットの日付時刻を表す文字列。YYYY-MM-DDTHH:MM:SS。 <br> 例: 2015-08-26T19:16:03 = 2015年8月26日19時16分03秒 | | 6 | date | ISO8611フォーマットの日付を表す文字列。YYYY-MM-DD。 <br> 例: 2015-08-26 = 2015年8月26日 | | 7 | datejun | 後述 |  #### datejun型  いい生活独自の日付と旬を表すフォーマット。YYYYMMJDD。  * YYYY: 西暦年 * MM: 月。01～12。ただし00とすることにより、年単位までの精度の数字を表現可能。 * J: 旬。1=上旬、2=中旬、3=下旬。 0とすることで月単位までの精度の数字を表現可能。 * DD: 日。01～31。ただし00とすることにより、旬単位までの精度の数字を表現可能。日単位の精度の場合、1～10日までは旬を1、11～20日までは旬を2、21日以降は旬を3と指定する必要がある。 * 例:     * 201900000 = 2019年     * 201901000 = 2019年1月     * 201903100 = 2019年3月上旬     * 201912300 = 2019年12月下旬     * 201906105 = 2019年6月5日     * 201908216 = 2019年8月16日  ## 検索パラメータ  ### OR 検索  パラメータタイプが `array` のキーについては、クエリパラメータで複数指定を行った場合、 指定された値のいずれかに一致する対象を検索する（ OR 検索）。  ex) `?layout_type_code=1&layout_type_code=2`  ### ソート順  `*.order` という名前のパラメータでソート順を指定可能。ascを指定したとき昇順、descを指定したとき降順となる。  ex) `?price.order=desc`  基本的にソート順は一つだけ指定する。
 *
 * The version of the OpenAPI document: 6.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DateJun,
  DateJunFromJSON,
  DateJunFromJSONTyped,
  DateJunToJSON,
  Deposit,
  DepositFromJSON,
  DepositFromJSONTyped,
  DepositToJSON,
  FreeRent,
  FreeRentFromJSON,
  FreeRentFromJSONTyped,
  FreeRentToJSON,
  Insurance,
  InsuranceFromJSON,
  InsuranceFromJSONTyped,
  InsuranceToJSON,
  OtherInitialCost,
  OtherInitialCostFromJSON,
  OtherInitialCostFromJSONTyped,
  OtherInitialCostToJSON,
  OtherMonthlyCost,
  OtherMonthlyCostFromJSON,
  OtherMonthlyCostFromJSONTyped,
  OtherMonthlyCostToJSON,
  Price,
  PriceFromJSON,
  PriceFromJSONTyped,
  PriceToJSON,
  PriceWithUnit,
  PriceWithUnitFromJSON,
  PriceWithUnitFromJSONTyped,
  PriceWithUnitToJSON,
  RenewalFee,
  RenewalFeeFromJSON,
  RenewalFeeFromJSONTyped,
  RenewalFeeToJSON,
  RentBrokerageAllocation,
  RentBrokerageAllocationFromJSON,
  RentBrokerageAllocationFromJSONTyped,
  RentBrokerageAllocationToJSON,
  RentPeriod,
  RentPeriodFromJSON,
  RentPeriodFromJSONTyped,
  RentPeriodToJSON,
  Tokuyuchin,
  TokuyuchinFromJSON,
  TokuyuchinFromJSONTyped,
  TokuyuchinToJSON,
} from './';

/**
 * 賃貸契約条件
 * @export
 * @interface RentContractCondition
 */
export interface RentContractCondition {
  /**
   * 現貸料
   * @type {Price}
   * @memberof RentContractCondition
   */
  price: Price;
  /**
   *
   * @type {Date}
   * @memberof RentContractCondition
   */
  priceUpdateDate?: Date;
  /**
   *
   * @type {number}
   * @memberof RentContractCondition
   */
  pricePerTsubo?: number;
  /**
   * 管理費
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  manageCost?: PriceWithUnit;
  /**
   * 共益費
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  serviceFee?: PriceWithUnit;
  /**
   *
   * @type {Deposit}
   * @memberof RentContractCondition
   */
  deposit?: Deposit;
  /**
   * 礼金
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  keyMoney?: PriceWithUnit;
  /**
   * 敷引金
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  repairCost?: PriceWithUnit;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly guaranteeAmortizationClass?: string;
  /**
   * 1: 年<br/>2: 更新時<br/>3: 解約時<br/>4: 契約時
   * @type {string}
   * @memberof RentContractCondition
   */
  guaranteeAmortizationClassCode?: string;
  /**
   * 保証金
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  guaranteePrice?: PriceWithUnit;
  /**
   * 償却金
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  amortizationExpense?: PriceWithUnit;
  /**
   * 権利金
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  premium?: PriceWithUnit;
  /**
   *
   * @type {number}
   * @memberof RentContractCondition
   */
  fixturesCost?: number;
  /**
   *
   * @type {Tokuyuchin}
   * @memberof RentContractCondition
   */
  tokuyuchin?: Tokuyuchin;
  /**
   *
   * @type {boolean}
   * @memberof RentContractCondition
   */
  isTokuyuchin?: boolean;
  /**
   *
   * @type {RenewalFee}
   * @memberof RentContractCondition
   */
  renewalFee?: RenewalFee;
  /**
   * 雑費
   * @type {PriceWithUnit}
   * @memberof RentContractCondition
   */
  miscExpense?: PriceWithUnit;
  /**
   *
   * @type {Insurance}
   * @memberof RentContractCondition
   */
  insurance?: Insurance;
  /**
   *
   * @type {boolean}
   * @memberof RentContractCondition
   */
  hasInsurance?: boolean;
  /**
   *
   * @type {RentBrokerageAllocation}
   * @memberof RentContractCondition
   */
  rentBrokerageAllocation?: RentBrokerageAllocation;
  /**
   *
   * @type {FreeRent}
   * @memberof RentContractCondition
   */
  freeRent?: FreeRent;
  /**
   *
   * @type {Array<OtherInitialCost>}
   * @memberof RentContractCondition
   */
  otherInitialCost: Array<OtherInitialCost>;
  /**
   *
   * @type {Array<OtherMonthlyCost>}
   * @memberof RentContractCondition
   */
  otherMonthlyCost: Array<OtherMonthlyCost>;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  otherCostComment?: string;
  /**
   *
   * @type {boolean}
   * @memberof RentContractCondition
   */
  initialCostCreditCardAvailableFlag?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RentContractCondition
   */
  monthlyCostCreditCardAvailableFlag?: boolean;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly initialCost?: string;
  /**
   * 1: 五万円以下<br/>2: 十万円以下<br/>3: 十五万円以下<br/>4: 二十万円以下<br/>5: 三十万円以下<br/>99: その他
   * @type {number}
   * @memberof RentContractCondition
   */
  initialCostCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  guarantorCompanyRequirements?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 必須
   * @type {number}
   * @memberof RentContractCondition
   */
  guarantorCompanyRequirementsCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  guarantorCompanyName?: string;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  guarantorCompanyContractDetail?: string;
  /**
   * 非推奨のため代わりにguarantor_requirements_codeを使うこと。
   * @type {boolean}
   * @memberof RentContractCondition
   */
  noGuarantorFlag?: boolean;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly guarantorRequirements?: string;
  /**
   * 1: 要<br/>2: 不要<br/>3: 未入力
   * @type {number}
   * @memberof RentContractCondition
   */
  guarantorRequirementsCode?: number;
  /**
   *
   * @type {RentPeriod}
   * @memberof RentContractCondition
   */
  rentPeriod?: RentPeriod;
  /**
   * 入居可能日／引渡可能日
   * @type {DateJun}
   * @memberof RentContractCondition
   */
  availableDatejun?: DateJun;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly available?: string;
  /**
   * 1: 即時<br/>2: 相談<br/>3: 期日指定<br/>4: 予定
   * @type {number}
   * @memberof RentContractCondition
   */
  availableCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly rentTransactionForm?: string;
  /**
   * 1: 貸主<br/>2: 代理<br/>3: 仲介元付(専任)<br/>4: 仲介元付(一般)<br/>5: 仲介先物<br/>6: 仲介元付<br/>7: 仲介
   * @type {number}
   * @memberof RentContractCondition
   */
  rentTransactionFormCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly studentRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談<br/>4: 限定<br/>5: 希望<br/>6: 歓迎
   * @type {number}
   * @memberof RentContractCondition
   */
  studentRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly genderRestriction?: string;
  /**
   * 1: 不問<br/>2: 女性限定<br/>3: 男性限定<br/>4: 女性希望<br/>5: 男性希望
   * @type {number}
   * @memberof RentContractCondition
   */
  genderRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly kidsRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  kidsRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly onePersonRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談<br/>4: 限定<br/>5: 希望
   * @type {number}
   * @memberof RentContractCondition
   */
  onePersonRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly twoPersonsRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談<br/>4: 限定<br/>5: 希望<br/>6: 歓迎
   * @type {number}
   * @memberof RentContractCondition
   */
  twoPersonsRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly elderRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談<br/>4: 限定<br/>5: 希望<br/>6: 歓迎
   * @type {number}
   * @memberof RentContractCondition
   */
  elderRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly corporateContractRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談<br/>4: 限定<br/>5: 希望
   * @type {number}
   * @memberof RentContractCondition
   */
  corporateContractRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly petRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  petRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly officeUsageRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  officeUsageRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly musicalInstrumentRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  musicalInstrumentRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly restaurantUsageRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  restaurantUsageRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly roomSharingRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  roomSharingRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly foreignerRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  foreignerRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly friendsRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  friendsRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly foreignStudentRestriction?: string;
  /**
   * 1: 不可<br/>2: 可<br/>3: 相談
   * @type {number}
   * @memberof RentContractCondition
   */
  foreignStudentRestrictionCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  readonly depositForStudent?: string;
  /**
   * 1: 不要<br/>2: 一ヶ月<br/>3: 二ヶ月
   * @type {number}
   * @memberof RentContractCondition
   */
  depositForStudentCode?: number;
  /**
   *
   * @type {string}
   * @memberof RentContractCondition
   */
  otherCondition?: string;
}

export function RentContractConditionFromJSON(
  json: any
): RentContractCondition {
  return RentContractConditionFromJSONTyped(json, false);
}

export function RentContractConditionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RentContractCondition {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    price: PriceFromJSON(json['price']),
    priceUpdateDate: !exists(json, 'price_update_date')
      ? undefined
      : new Date(json['price_update_date']),
    pricePerTsubo: !exists(json, 'price_per_tsubo')
      ? undefined
      : json['price_per_tsubo'],
    manageCost: !exists(json, 'manage_cost')
      ? undefined
      : PriceWithUnitFromJSON(json['manage_cost']),
    serviceFee: !exists(json, 'service_fee')
      ? undefined
      : PriceWithUnitFromJSON(json['service_fee']),
    deposit: !exists(json, 'deposit')
      ? undefined
      : DepositFromJSON(json['deposit']),
    keyMoney: !exists(json, 'key_money')
      ? undefined
      : PriceWithUnitFromJSON(json['key_money']),
    repairCost: !exists(json, 'repair_cost')
      ? undefined
      : PriceWithUnitFromJSON(json['repair_cost']),
    guaranteeAmortizationClass: !exists(json, 'guarantee_amortization_class')
      ? undefined
      : json['guarantee_amortization_class'],
    guaranteeAmortizationClassCode: !exists(
      json,
      'guarantee_amortization_class_code'
    )
      ? undefined
      : json['guarantee_amortization_class_code'],
    guaranteePrice: !exists(json, 'guarantee_price')
      ? undefined
      : PriceWithUnitFromJSON(json['guarantee_price']),
    amortizationExpense: !exists(json, 'amortization_expense')
      ? undefined
      : PriceWithUnitFromJSON(json['amortization_expense']),
    premium: !exists(json, 'premium')
      ? undefined
      : PriceWithUnitFromJSON(json['premium']),
    fixturesCost: !exists(json, 'fixtures_cost')
      ? undefined
      : json['fixtures_cost'],
    tokuyuchin: !exists(json, 'tokuyuchin')
      ? undefined
      : TokuyuchinFromJSON(json['tokuyuchin']),
    isTokuyuchin: !exists(json, 'is_tokuyuchin')
      ? undefined
      : json['is_tokuyuchin'],
    renewalFee: !exists(json, 'renewal_fee')
      ? undefined
      : RenewalFeeFromJSON(json['renewal_fee']),
    miscExpense: !exists(json, 'misc_expense')
      ? undefined
      : PriceWithUnitFromJSON(json['misc_expense']),
    insurance: !exists(json, 'insurance')
      ? undefined
      : InsuranceFromJSON(json['insurance']),
    hasInsurance: !exists(json, 'has_insurance')
      ? undefined
      : json['has_insurance'],
    rentBrokerageAllocation: !exists(json, 'rent_brokerage_allocation')
      ? undefined
      : RentBrokerageAllocationFromJSON(json['rent_brokerage_allocation']),
    freeRent: !exists(json, 'free_rent')
      ? undefined
      : FreeRentFromJSON(json['free_rent']),
    otherInitialCost: (json['other_initial_cost'] as Array<any>).map(
      OtherInitialCostFromJSON
    ),
    otherMonthlyCost: (json['other_monthly_cost'] as Array<any>).map(
      OtherMonthlyCostFromJSON
    ),
    otherCostComment: !exists(json, 'other_cost_comment')
      ? undefined
      : json['other_cost_comment'],
    initialCostCreditCardAvailableFlag: !exists(
      json,
      'initial_cost_credit_card_available_flag'
    )
      ? undefined
      : json['initial_cost_credit_card_available_flag'],
    monthlyCostCreditCardAvailableFlag: !exists(
      json,
      'monthly_cost_credit_card_available_flag'
    )
      ? undefined
      : json['monthly_cost_credit_card_available_flag'],
    initialCost: !exists(json, 'initial_cost')
      ? undefined
      : json['initial_cost'],
    initialCostCode: !exists(json, 'initial_cost_code')
      ? undefined
      : json['initial_cost_code'],
    guarantorCompanyRequirements: !exists(
      json,
      'guarantor_company_requirements'
    )
      ? undefined
      : json['guarantor_company_requirements'],
    guarantorCompanyRequirementsCode: !exists(
      json,
      'guarantor_company_requirements_code'
    )
      ? undefined
      : json['guarantor_company_requirements_code'],
    guarantorCompanyName: !exists(json, 'guarantor_company_name')
      ? undefined
      : json['guarantor_company_name'],
    guarantorCompanyContractDetail: !exists(
      json,
      'guarantor_company_contract_detail'
    )
      ? undefined
      : json['guarantor_company_contract_detail'],
    noGuarantorFlag: !exists(json, 'no_guarantor_flag')
      ? undefined
      : json['no_guarantor_flag'],
    guarantorRequirements: !exists(json, 'guarantor_requirements')
      ? undefined
      : json['guarantor_requirements'],
    guarantorRequirementsCode: !exists(json, 'guarantor_requirements_code')
      ? undefined
      : json['guarantor_requirements_code'],
    rentPeriod: !exists(json, 'rent_period')
      ? undefined
      : RentPeriodFromJSON(json['rent_period']),
    availableDatejun: !exists(json, 'available_datejun')
      ? undefined
      : DateJunFromJSON(json['available_datejun']),
    available: !exists(json, 'available') ? undefined : json['available'],
    availableCode: !exists(json, 'available_code')
      ? undefined
      : json['available_code'],
    rentTransactionForm: !exists(json, 'rent_transaction_form')
      ? undefined
      : json['rent_transaction_form'],
    rentTransactionFormCode: !exists(json, 'rent_transaction_form_code')
      ? undefined
      : json['rent_transaction_form_code'],
    studentRestriction: !exists(json, 'student_restriction')
      ? undefined
      : json['student_restriction'],
    studentRestrictionCode: !exists(json, 'student_restriction_code')
      ? undefined
      : json['student_restriction_code'],
    genderRestriction: !exists(json, 'gender_restriction')
      ? undefined
      : json['gender_restriction'],
    genderRestrictionCode: !exists(json, 'gender_restriction_code')
      ? undefined
      : json['gender_restriction_code'],
    kidsRestriction: !exists(json, 'kids_restriction')
      ? undefined
      : json['kids_restriction'],
    kidsRestrictionCode: !exists(json, 'kids_restriction_code')
      ? undefined
      : json['kids_restriction_code'],
    onePersonRestriction: !exists(json, 'one_person_restriction')
      ? undefined
      : json['one_person_restriction'],
    onePersonRestrictionCode: !exists(json, 'one_person_restriction_code')
      ? undefined
      : json['one_person_restriction_code'],
    twoPersonsRestriction: !exists(json, 'two_persons_restriction')
      ? undefined
      : json['two_persons_restriction'],
    twoPersonsRestrictionCode: !exists(json, 'two_persons_restriction_code')
      ? undefined
      : json['two_persons_restriction_code'],
    elderRestriction: !exists(json, 'elder_restriction')
      ? undefined
      : json['elder_restriction'],
    elderRestrictionCode: !exists(json, 'elder_restriction_code')
      ? undefined
      : json['elder_restriction_code'],
    corporateContractRestriction: !exists(
      json,
      'corporate_contract_restriction'
    )
      ? undefined
      : json['corporate_contract_restriction'],
    corporateContractRestrictionCode: !exists(
      json,
      'corporate_contract_restriction_code'
    )
      ? undefined
      : json['corporate_contract_restriction_code'],
    petRestriction: !exists(json, 'pet_restriction')
      ? undefined
      : json['pet_restriction'],
    petRestrictionCode: !exists(json, 'pet_restriction_code')
      ? undefined
      : json['pet_restriction_code'],
    officeUsageRestriction: !exists(json, 'office_usage_restriction')
      ? undefined
      : json['office_usage_restriction'],
    officeUsageRestrictionCode: !exists(json, 'office_usage_restriction_code')
      ? undefined
      : json['office_usage_restriction_code'],
    musicalInstrumentRestriction: !exists(
      json,
      'musical_instrument_restriction'
    )
      ? undefined
      : json['musical_instrument_restriction'],
    musicalInstrumentRestrictionCode: !exists(
      json,
      'musical_instrument_restriction_code'
    )
      ? undefined
      : json['musical_instrument_restriction_code'],
    restaurantUsageRestriction: !exists(json, 'restaurant_usage_restriction')
      ? undefined
      : json['restaurant_usage_restriction'],
    restaurantUsageRestrictionCode: !exists(
      json,
      'restaurant_usage_restriction_code'
    )
      ? undefined
      : json['restaurant_usage_restriction_code'],
    roomSharingRestriction: !exists(json, 'room_sharing_restriction')
      ? undefined
      : json['room_sharing_restriction'],
    roomSharingRestrictionCode: !exists(json, 'room_sharing_restriction_code')
      ? undefined
      : json['room_sharing_restriction_code'],
    foreignerRestriction: !exists(json, 'foreigner_restriction')
      ? undefined
      : json['foreigner_restriction'],
    foreignerRestrictionCode: !exists(json, 'foreigner_restriction_code')
      ? undefined
      : json['foreigner_restriction_code'],
    friendsRestriction: !exists(json, 'friends_restriction')
      ? undefined
      : json['friends_restriction'],
    friendsRestrictionCode: !exists(json, 'friends_restriction_code')
      ? undefined
      : json['friends_restriction_code'],
    foreignStudentRestriction: !exists(json, 'foreign_student_restriction')
      ? undefined
      : json['foreign_student_restriction'],
    foreignStudentRestrictionCode: !exists(
      json,
      'foreign_student_restriction_code'
    )
      ? undefined
      : json['foreign_student_restriction_code'],
    depositForStudent: !exists(json, 'deposit_for_student')
      ? undefined
      : json['deposit_for_student'],
    depositForStudentCode: !exists(json, 'deposit_for_student_code')
      ? undefined
      : json['deposit_for_student_code'],
    otherCondition: !exists(json, 'other_condition')
      ? undefined
      : json['other_condition'],
  };
}

export function RentContractConditionToJSON(
  value?: RentContractCondition | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    price: PriceToJSON(value.price),
    price_update_date:
      value.priceUpdateDate === undefined
        ? undefined
        : value.priceUpdateDate.toISOString(),
    price_per_tsubo: value.pricePerTsubo,
    manage_cost: PriceWithUnitToJSON(value.manageCost),
    service_fee: PriceWithUnitToJSON(value.serviceFee),
    deposit: DepositToJSON(value.deposit),
    key_money: PriceWithUnitToJSON(value.keyMoney),
    repair_cost: PriceWithUnitToJSON(value.repairCost),
    guarantee_amortization_class_code: value.guaranteeAmortizationClassCode,
    guarantee_price: PriceWithUnitToJSON(value.guaranteePrice),
    amortization_expense: PriceWithUnitToJSON(value.amortizationExpense),
    premium: PriceWithUnitToJSON(value.premium),
    fixtures_cost: value.fixturesCost,
    tokuyuchin: TokuyuchinToJSON(value.tokuyuchin),
    is_tokuyuchin: value.isTokuyuchin,
    renewal_fee: RenewalFeeToJSON(value.renewalFee),
    misc_expense: PriceWithUnitToJSON(value.miscExpense),
    insurance: InsuranceToJSON(value.insurance),
    has_insurance: value.hasInsurance,
    rent_brokerage_allocation: RentBrokerageAllocationToJSON(
      value.rentBrokerageAllocation
    ),
    free_rent: FreeRentToJSON(value.freeRent),
    other_initial_cost: (value.otherInitialCost as Array<any>).map(
      OtherInitialCostToJSON
    ),
    other_monthly_cost: (value.otherMonthlyCost as Array<any>).map(
      OtherMonthlyCostToJSON
    ),
    other_cost_comment: value.otherCostComment,
    initial_cost_credit_card_available_flag:
      value.initialCostCreditCardAvailableFlag,
    monthly_cost_credit_card_available_flag:
      value.monthlyCostCreditCardAvailableFlag,
    initial_cost_code: value.initialCostCode,
    guarantor_company_requirements: value.guarantorCompanyRequirements,
    guarantor_company_requirements_code: value.guarantorCompanyRequirementsCode,
    guarantor_company_name: value.guarantorCompanyName,
    guarantor_company_contract_detail: value.guarantorCompanyContractDetail,
    no_guarantor_flag: value.noGuarantorFlag,
    guarantor_requirements_code: value.guarantorRequirementsCode,
    rent_period: RentPeriodToJSON(value.rentPeriod),
    available_datejun: DateJunToJSON(value.availableDatejun),
    available_code: value.availableCode,
    rent_transaction_form_code: value.rentTransactionFormCode,
    student_restriction_code: value.studentRestrictionCode,
    gender_restriction_code: value.genderRestrictionCode,
    kids_restriction_code: value.kidsRestrictionCode,
    one_person_restriction_code: value.onePersonRestrictionCode,
    two_persons_restriction_code: value.twoPersonsRestrictionCode,
    elder_restriction_code: value.elderRestrictionCode,
    corporate_contract_restriction_code: value.corporateContractRestrictionCode,
    pet_restriction_code: value.petRestrictionCode,
    office_usage_restriction_code: value.officeUsageRestrictionCode,
    musical_instrument_restriction_code: value.musicalInstrumentRestrictionCode,
    restaurant_usage_restriction_code: value.restaurantUsageRestrictionCode,
    room_sharing_restriction_code: value.roomSharingRestrictionCode,
    foreigner_restriction_code: value.foreignerRestrictionCode,
    friends_restriction_code: value.friendsRestrictionCode,
    foreign_student_restriction_code: value.foreignStudentRestrictionCode,
    deposit_for_student_code: value.depositForStudentCode,
    other_condition: value.otherCondition,
  };
}
