import { BuildingPropertyPreview } from '@/dejima/property';

export default {
  buildingGuid: '29cf73b8-5006-4b58-9958-45c8a56423ef',
  buildingFurigana: 'プライベートプレイスヒロオ',
  buildingName: 'プライベートプレイス広尾',
  buildingClass: '集合住宅',
  buildingClassCode: 2,
  buildingType: 'マンション',
  buildingTypeCode: 1,
  structure: '鉄筋コンクリート',
  structureCode: 3,
  groundFloors: 3,
  completionDatejun: {
    value: 201901000,
    year: 2019,
    month: 1,
    jun: 0,
    text: '2019年1月',
  },
  zipcodeText: '1500012',
  jisCodeValue: 13113,
  prefecture: '東京都',
  prefectureCode: 13,
  city: '渋谷区',
  cityCode: 113,
  town: '広尾',
  tyoume: '１丁目',
  addressText: '東京都渋谷区広尾１丁目',
  branchNumberText: '1-22',
  latitude: 128336584,
  longitude: 502967253,
  parallel2ParkingFlag: false,
  parallel3ParkingFlag: false,
  hasLargeGarage: false,
  hasVisitorsParking: false,
  hasGarage: false,
  hasDeliveryBox: true,
  propertyTotalCounts: 8,
  property: [
    {
      propertyFullKey: '1120109515530002777959',
      propertyClass: '区画',
      propertyClassCode: 3,
      propertyUse: '居住用',
      propertyUseCode: 1,
      propertyType: 'マンション',
      propertyTypeCode: 101,
      roomNumberText: '102',
      isPublished: true,
      publishedDatetime: new Date('2020-04-27T16:41:13.000Z'),
      lastUpdateDatetime: new Date('2020-04-27T16:41:13.000Z'),
      nextRenewalDatetime: new Date('2020-05-27T16:41:13.000Z'),
      hasEntries: false,
      currentStatus: '空室',
      currentStatusCode: 2,
      nameDisplayFlag: true,
      roomNumberDisplayFlag: false,
      branchNumberDisplayFlag: false,
      mapMarkerDisplayFlag: false,
      panoramaFlag: false,
      houseWithOfficeFlag: false,
      houseWithShopsFlag: false,
      itJusetsuFlag: false,
      gas: '都市ガス',
      gasCode: 1,
      rentTransactionForm: '仲介先物',
      rentTransactionFormCode: 5,
      residenceRentPeriod: '普通借家契約',
      residenceRentPeriodCode: 1,
      newUsed: '中古',
      newUsedCode: 2,
      price: {
        amount: 284000,
      },
      priceUpdateDate: new Date('2020-04-25T09:53:22.000Z'),
      miscExpense: {
        unit: '円',
      },
      hasInsurance: true,
      insurance: {
        insuranceMonth: 24,
        insuranceName: '家財保険',
        insurancePrice: {
          amount: 20000,
        },
      },
      keyMoney: {
        amount: 1,
        unit: 'ヶ月',
      },
      deposit: {
        amount: 0,
        unit: 'ヶ月',
        additionalDeposit: {
          unit: 'ヶ月',
        },
      },
      repairCost: {
        unit: 'ヶ月',
      },
      guaranteePrice: {
        unit: 'ヶ月',
      },
      amortizationExpense: {
        unit: 'ヶ月',
      },
      premium: {
        unit: 'ヶ月',
      },
      manageCost: {
        unit: '円',
      },
      serviceFee: {
        amount: 10500,
        unit: '円',
      },
      initialCostCreditCardAvailableFlag: true,
      monthlyCostCreditCardAvailableFlag: false,
      otherInitialCostFreeFlag: false,
      manageCostFreeCode: 0,
      serviceFeeFree: '有',
      serviceFeeFreeCode: 1,
      miscExpenseFreeCode: 0,
      noGuarantorFlag: true,
      guarantorRequirements: '不要',
      guarantorRequirementsCode: 2,
      initialCost: 'その他',
      initialCostCode: 99,
      studentRestriction: '相談',
      studentRestrictionCode: 3,
      genderRestriction: '不問',
      genderRestrictionCode: 1,
      kidsRestriction: '相談',
      kidsRestrictionCode: 3,
      onePersonRestriction: '可',
      onePersonRestrictionCode: 2,
      twoPersonsRestriction: '可',
      twoPersonsRestrictionCode: 2,
      corporateContractRestriction: '可',
      corporateContractRestrictionCode: 2,
      foreignerRestriction: '相談',
      foreignerRestrictionCode: 3,
      foreignStudentRestriction: '相談',
      foreignStudentRestrictionCode: 3,
      roomCount: 1,
      layoutType: 'SDK',
      layoutTypeCode: 4,
      layoutText: '1SDK',
      orientation: '北',
      orientationCode: 4,
      floorNumber: '1',
      exclusiveArea: {
        area: 57.44,
        measurementMethod: '壁芯',
      },
      available: '相談',
      availableCode: 2,
      salesPoint:
        '仲介手数料は半月分（税別）テレビ、洗濯機、冷蔵庫、掃除機、ベット、机、イス、ドライヤー、カーテンなどの家具・家電が付いているので、入居したその日から生活できます。',
      originalPropertyCodeText: '-2000003849516',
      advertisingFee: {
        unit: 'ヶ月',
      },
      customerKey: 2101962,
      agentGuid: 'fe69a0ca-036f-4f9c-b8d6-680f3d0b5989',
      transportation: [
        {
          transportationKind: '鉄道を利用',
          transportationKindCode: 1,
          wayTo: '徒歩',
          wayToCode: 1,
          station: {
            stationCode: '1970',
            stationName: '恵比寿（東京）',
            lineCode: '125',
            lineName: '山手線',
            companyName: 'ＪＲ東日本',
          },
          stationAccess: {
            value: 6,
            unit: '分',
          },
        },
        {
          transportationKind: '鉄道を利用',
          transportationKindCode: 1,
          wayTo: '徒歩',
          wayToCode: 1,
          station: {
            stationCode: '2338',
            stationName: '広尾',
            lineCode: '215',
            lineName: '東京メトロ日比谷線',
            companyName: '東京メトロ',
          },
          stationAccess: {
            value: 13,
            unit: '分',
          },
        },
        {
          transportationKind: '鉄道を利用',
          transportationKindCode: 1,
          wayTo: '徒歩',
          wayToCode: 1,
          station: {
            stationCode: '3447',
            stationName: '渋谷',
            lineCode: '123',
            lineName: '埼京線',
            companyName: 'ＪＲ東日本',
          },
          stationAccess: {
            value: 19,
            unit: '分',
          },
        },
      ],
      hasBikeParking: true,
      hasMotorbikeParking: false,
      parkingPriceRange: {},
      searchArea: 57.44,
      pickupFeature: {
        isFurnished: true,
        hasAppliances: true,
        isNetFree: true,
        isOver2f: false,
        isBathToiletSeparate: true,
        hasAircon: true,
        hasAutoLock: true,
        hasElevator: false,
        hasLandryRoom: true,
        isFlooring: true,
        isDesignersApartment: true,
        isBarrierFree: false,
        isSouthFacing: false,
        isHighestFloor: false,
        isCornerRoom: false,
        hasSystemKitchen: true,
        hasIhStove: true,
        hasGasStove: true,
        hasMultipleGasStove: true,
        hasReboilBath: false,
        hasWashlet: true,
        hasBathDryer: true,
        hasFloorHeating: false,
        hasCloset: true,
        hasWalkInCloset: true,
        hasCatv: false,
        hasCs: false,
        hasBs: false,
        hasOpticalFiber: true,
        isAllElectric: false,
        hasWashroom: true,
        isNoBuildingInFront: false,
        hasVerandaBalcony: false,
      },
    },
  ],
} as BuildingPropertyPreview;
